{host_spec,"c200",
 [{hostname,"c200"},
  {local_ip,"192.168.1.200"},
  {ssh_port,22},
  {uid,"ubuntu"},
  {passwd,"festum01"},
  {application_config,[]},
  {connect_node_name,"host_controller"},
  {connect_node,'host_controller@c200'}
 ]
}.
