{host_spec,"c202",
 [{hostname,"c202"},
   {local_ip,"192.168.1.202"},
   {ssh_port,22},
   {uid,"ubuntu"},
   {passwd,"festum01"},
   {application_config,[]},
   {connect_node_name,"host_controller"},
   {connect_node,'host_controller@c202'}
 ]
}.
